version: "3"
services:
  nginx-php:
    image: yoonaisu/nginx-php:7.4
    restart: always
    ports:
      - "8080:80"
      - "4443:443"
    networks:
      - laravel
    volumes:
      - ./wwwroot:/data/wwwroot
      - ./wwwlogs:/data/wwwlogs
      - ./ssl:/data/server/nginx/ssl
      - ./vhost:/data/server/nginx/vhost
  # 如果需要mysql
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - laravel

volumes:
  db_data: {}

networks:
  laravel:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"